# [Showcase] {#sec-appendix-a}

```{r}
#| label: Setup
#| include: false

library(here)
library(lorem)
library(stringr)
library(withr)

here("R", ".setup.R") |> source()
```

```{r}
#| echo: false
#| output: asis

library(lorem)
library(stringr)
library(withr)

with_seed(
  seed = 454545,
  code = {
    ipsum(1, avg_words_per_sentence = 28) |>
      as.character() |>
      str_remove(".$") |>
      paste0(" [@vonneumann1993a].") |>
      cat(sep = "\n\n")
  }
)
```

## Heading 2

```{r}
#| echo: false
#| output: asis

library(lorem)
library(stringr)
library(withr)

with_seed(
  seed = 254895,
  code = {
    ipsum(1, avg_words_per_sentence = 14) |>
      as.character() |>
      str_remove(".$") |>
      paste0(" [@lorenz1963].") |>
      cat(sep = "\n\n")
  }
)
```

### Heading 3

```{r}
#| echo: false
#| output: asis

library(lorem)
library(stringr)
library(withr)

with_seed(
  seed = 89794514,
  code = {
    ipsum(1, avg_words_per_sentence = 18) |>
      as.character() |>
      str_remove(".$") |>
      paste0(" [@hinton1986].") |>
      cat(sep = "\n\n")
  }
)
```

```{=latex}
\end{apendicesenv}
```

<!-- appendices end -->

```{=latex}
\begin{anexosenv}
```
