# [Showcase] Conclusion {#sec-conclusion}

```{r}
#| label: Setup
#| include: false

library(here)
library(lorem)
library(stringr)
library(withr)

here("R", ".setup.R") |> source()
```

```{=latex}
\epigraph{Every genuine test of a theory is an attempt to falsify it, or to refute it.}{--- \textcite{popper2002}}

\vspace*{-1\baselineskip}

\epigraph{I suggest that it is the aim of science to find satisfactory explanations, of whatever strikes us as being in need of explanation.}{--- \textcite[193]{popper1979a}}
```

<!-- @popper2002 -->
<!-- @popper1979a -->

```{r}
#| echo: false
#| output: asis

library(lorem)
library(stringr)
library(withr)

with_seed(
  seed = 86521,
  code = {
    ipsum(1, avg_words_per_sentence = 30) |>
      as.character() |>
      str_remove(".$") |>
      paste0(" [@gell-mann2023].") |>
      cat(sep = "\n\n")
  }
)
```

## Heading 2

```{r}
#| echo: false
#| output: asis

library(lorem)
library(stringr)
library(withr)

with_seed(
  seed = 1252543,
  code = {
    c(
      ipsum(1, avg_words_per_sentence = 12) |>
        as.character() |>
        str_remove(".$") |>
        paste0(" [@lecun2015]."),
      ipsum(1, avg_words_per_sentence = 14) |>
        as.character() |>
        str_remove(".$") |>
        paste0(" [@foster1972].")
    ) |>
      cat(sep = "\n\n")
  }
)
```

### Heading 3

```{r}
#| echo: false
#| output: asis

library(lorem)
library(stringr)
library(withr)

with_seed(
  seed = 548791,
  code = {
    ipsum(1, avg_words_per_sentence = 10) |>
      as.character() |>
      str_remove(".$") |>
      paste0(" [@more2014].") |>
      cat(sep = "\n\n")
  }
)
```

- Bullet point
  - Bullet point
    - Bullet point

#### Heading 4

```{r}
#| echo: false
#| output: asis

library(lorem)
library(stringr)
library(withr)

with_seed(
  seed = 13548,
  code = {
    ipsum(1, avg_words_per_sentence = 15) |>
      as.character() |>
      str_remove(".$") |>
      paste0(" [@papert2020].") |>
      paste0(" See @tbl-error-types.") |>
      cat(sep = "\n\n")
  }
)
```

1. List
1. List
1. List

##### Heading 5

```{r}
#| echo: false
#| output: asis

library(lorem)
library(stringr)
library(withr)

with_seed(
  seed = 3758,
  code = {
    ipsum(1, avg_words_per_sentence = 5) |>
      as.character() |>
      str_remove(".$") |>
      paste0(" [@tisue2004; @tisue2004a].") |>
      cat(sep = "\n\n")
  }
)
```

<!-- textual end -->

```{=latex}
\postextual

\begingroup
\renewcommand{\baselinestretch}{1}
\setcounter{footnote}{0}
\renewcommand{\thefootnote}{\fnsymbol{footnote}}

\printbibliography[
  heading=bibheading
]

\endgroup

\tocskipone
\tocprintchapternonum
\addcontentsline{toc}{chapter}{\newbibname}
```

```{=latex}
\begin{glossario}
```
