<!-- %:::% .common h1 begin %:::% -->
# LIST OF TERMS AND DEFINITIONS {.unnumbered}
<!-- %:::% .common h1 end %:::% -->

```{r}
#| label: setup
#| echo: false
#| output: false

# library(here)

source(here::here("R/quarto-setup.R"))
```

::: {.callout-warning}
The text below is for demonstrative purposes only.

See <https://github.com/danielvartan/tesesusp> to learn more about this template.
:::

<!-- TODO -->
<!-- * Insert definition from other areas of science. -->

<!-- %:::% list-of-terms body begin %:::% -->
<!-- @aschoff1965; @marques2012 -->
For an extensive list of chronobiology terms and definitions, please refer to Aschoff et al. (1965) and Marques & Oda (2012).

<!-- @ehret1974; @pittendrigh1993; @horne1976; @roenneberg2003; @roenneberg2012a -->
Chronotype
: \hspace{20cm} Any kind of temporal phenotype (Ehret, 1974; Pittendrigh, 1993). Usually, it refers to circadian phenotypes in a spectrum that goes from morningness to eveningness (Horne & Ostberg, 1976; Roenneberg et al., 2003). It can also be seen as an organism's phase of entrainment (Roenneberg et al., 2012).

<!-- @pittendrigh1960; @latinitium -->
Circadian rhythm
: \hspace{20cm} A rhythm with a period close to a day/24h, an approximation to the period of the earth's rotation (Pittendrigh, 1960). From the Latin _circā_, around, and _dĭes_, day (Latinitium, n.d.). Example: the sleep-wake cycle.

<!-- @mitchell2013 -->
Complex system
: \hspace{20cm} There are several definitions. Here are some that I found to be of use:

* "Systems that don't yield to compact forms of representation or description." (David Krakauer apud Mitchell, 2013)
* "A system of many interacting parts where the system is more than just the sum of its parts" (Mark Newman apud Mitchell, 2013)
* Systems with many connected agents that interact and exhibit self-organization and emergence behavior, all without the need for a central controller (adapted from Camilo Rodrigues Neto's definition, supervisor of this thesis).
* Dialectics at its finest (my working definition).

<!-- @kuhlman2018 -->
Entrainment
: \hspace{20cm} A shift and alignment of biological rhythms induced by a zeitgeber input (Kuhlman et al., 2018). For example: a shift/alignment of an organism's circadian rhythm when exposed to light.

<!-- Genotype -->

<!-- @latinitium -->
Infradian rhythm
: \hspace{20cm} A rhythm with a period greater than a day/24h. From the Latin _infrā_, below (think in terms of period repetition), and _dĭes_, day (Latinitium, n.d.). Example: the menstrual cycle.

<!-- @kuhlman2018 -->
Period
: \hspace{20cm} Cycle duration of an oscillation or, in a more technical way, the duration between two identical and consecutive phases in an oscillation (Kuhlman et al., 2018).

<!-- Phenotype -->

<!-- @bertalanffy1968; @levins1998 -->
System theory
: \hspace{20cm} Two definitions can be of use:

* Science or discipline that investigates models, principles, and laws that are valid to systems in general (Bertalanffy, 1968).
* "The attempt of a reductionist scientific tradition to come to terms with complexity, nonlinearity, and change through sophisticated mathematical and computational techniques, _a groping toward a more dialectical understanding_ that is held back by its philosophical biases and the institutional and economic contexts of its development." (Levins, 1998)

<!-- @latinitium -->
Ultradian rhythm
: \hspace{20cm} A rhythm with a period below a day/24h. From the Latin _ultrā_, beyond (think in terms of period repetition), and _dĭes_, day (Latinitium, n.d.). Example: the cardiac cycle.

<!-- @cambridgeuniversitypress; @pittendrigh1960 -->
Zeitgeber
: \hspace{20cm} Any periodic environmental signal/cue that can influence or regulate biological rhythms. From the German _zeit_, time, and _geber_, donor (Cambridge University Press, n.d.). Two main well known zeitgebers are light exposure and environment temperature (Pittendrigh, 1960).
<!-- %:::% list-of-terms body end %:::% -->
