# Settings {#sec-settings}

```{r}
#| label: Setup
#| include: false

library(here)

here("R", ".setup.R") |> source()
```

::: {.callout-note}
Please note that not all settings are documented. For issues or discussions, use the [*Issues*](https://github.com/danielvartan/abnt/issues) and [*Discussions*](https://github.com/danielvartan/abnt/discussions) tabs in the project 's GitHub repository.

For more information, check the format [extension YAML file](https://github.com/danielvartan/abnt/blob/main/_extensions/abnt/_extension.yml) and the [PDF Options](https://quarto.org/docs/reference/formats/pdf.html) section in the Quarto guide.
:::

## PDF Engine

This format uses [`lualatex`](https://www.luatex.org/). I recommend always using this engine for better font handling and feature support.

## Typography

```{=latex}
\index{typography}
```

### Typefaces

To change typefaces, use Quarto [PDF options](https://quarto.org/docs/reference/formats/pdf.html) like `mainfont`, `monofont`, and `sansfont`.

```yaml
format:
  abnt-pdf:
    mainfont: Arial
```

The ABNT NBR 14724:2011 norm does not specify a required font. You can use any font installed on your computer.

To list all fonts installed on your system, run the following in R:

```r
# install.packages("systemfonts")
library(systemfonts)

system_fonts()
```

### Font Size and Line-Height

Use `fontsize` and `linestretch` in `_quarto.yml` to adjust these options.

```yaml
format:
  abnt-pdf:
    fontsize: 12pt
    linestretch: 1.5
```

Note that Section 5.1 of the ABNT NBR 14724:2011 norm specifies that the font size should be **12pt** for the entire document, including the cover, except for quotations longer than three lines, footnotes, pagination, cataloging data, captions, and sources of illustrations and tables, which should be in a smaller and uniform size.

## Language and Hyphenation

```{=latex}
\index{language}
```

This format includes built-in support for multiple languages and hyphenation patterns, which are automatically loaded based on the document's language setting.

```yaml
format:
  abnt-pdf:
    lang: en
    babel-lang: english
    other-babel-lang: # Do not repeat 'babel-lang' here.
      - french
      - spanish
      - brazil
```

## Document Sections

### Pre-Textual Sections

`abnt` uses a system of tags to transfer and render the content of Quarto files to LaTeX. These tags look like this:

```
%:::% class attribute begin/end %:::%
```

Unless you want to customize the template, you don't need to modify the `.tex` files. You can write directly in the `.qmd` files. Just ensure that you preserve all the tags.

### Customizing the Sections

I plan to implement this format more straightforwardly using [Lua filters](https://quarto.org/docs/extensions/filters.html) to directly manipulate the LaTeX code generated by [Pandoc](https://pandoc.org/lua-filters.html). Until then, you can customize the sections using the following instructions.

#### Removing Pre-Textual Sections

If you don't need a pre-textual section (e.g., Errata, Acknowledgments), remove it from `tex/include-before-body.tex`, and `R/.pre-render.R`.

#### Removing Textual Sections

For textual sections (e.g., chapters), remove them from the `_quarto.yml` file, but be careful when removing the last chapter. See the next section for more details.

#### Removing Post-Textual Sections


Exercise caution when removing post-textual sections (e.g., Glossary, Appendices, Annexes). Each section begins and ends with specific LaTeX commands (e.g., `\begin{anexosenv}`).

To remove the Glossary:

1. Delete it from `_quarto.yml`
2. Remove the `\begin{glossario}` LaTeX code at the end of the *Conclusion* or last chapter
3. Copy the LaTeX code following `\begin{apendicesenv}` in `glossary.qmd` to the bottom of the *Conclusion* or last chapter

The same process applies when removing Appendices and Annexes. The last appendix must include LaTeX code to close the section and initialize the Annexes section.

The Index section is an exception. To remove it, add the following to your `_quarto.yml` file:

```yaml
format:
  abnt-pdf:
    index-page: false
```

In summary, transitions between document sections are created by inserting LaTeX code at the end of specific sections:

- Between the last chapter and the Glossary
- Between the Glossary and Appendices
- Between Appendices and Annexes
- At the end of the Annexes

## Citation Management

### Methods

This Quarto format is specifically designed along with [BibLaTeX](https://www.ctan.org/pkg/biblatex). For detailed guidance on handling citations, refer to Quarto's [Citation & Footnotes](https://quarto.org/docs/authoring/footnotes-and-citations.html) documentation.

```{=latex}
\index{BibLaTeX}
```

### Styles

```{=latex}
\index{ABNT}
\index{APA}
```

This format works with all [BibLaTeX](https://www.ctan.org/pkg/biblatex) built-in styles, including [ABNT](https://www.abnt.org.br/) (Brazilian Association of Technical Standards) and [APA](https://apastyle.apa.org/) (American Psychological Association).

To use a specific style, change the `biblatexoptions` option in the `_quarto.yml` file. Several citation-related options are available. Refer to the [`biblatex`](https://www.ctan.org/pkg/biblatex) manual for complete documentation.

```yaml
format:
  abnt-pdf:
    biblatexoptions:
      - backend=biber
      - url=true
      - isbn=true
      - useprefix=false
      - giveninits=true
      - style=abnt
    bibhang: 0cm # Use 0.5cm if `style=apa`
    bibparsep: -2ex # Use 1ex `style=apa`
    biblio-footnote: >
      According to the Brazilian Association of Technical Standards
      (ABNT NBR 6023).
```

### Zotero & Better BibTex

If you use [Zotero](https://www.zotero.org/) with [Better BibTex](https://retorque.re/zotero-better-bibtex/), configure it to export URLs only when no DOI is available. This helps declutter the References section. See <https://tex.stackexchange.com/a/603358/234832> for instructions.

## Figures and Tables

To add top and bottom captions to figures and tables, enclose your content in `divs` as shown below. The first paragraph after the content will be rendered as the source (bottom caption), and the last paragraph will be the top caption.

```md
::: {#fig-1}
::: {.figure-content}
This is the figure content.
:::

[This is the source.]{.legend}

This is the caption
:::
```

For figures/tables rendered in code chunks, use the following format:

````markdown
::: {#fig-2}
```{{r}}
library(dplyr)

penguins |>
  pull(bill_length_mm) |>
  hist()
```

[This is the source.]{.legend}

This is the caption
:::
````

Note that when using `[]{.legend}` or `[]{.legendleft}` the caption will always start with `Source: `.

Like all cross-reference elements, these `divs` must follow a naming pattern. Use the prefix `#fig-` for figures and `#tbl-` for tables. For more information, see the [*Cross-Referenceable Elements*](#cross-referenceable-elements) section and refer to Quarto's [Cross-Referenceable Elements](https://quarto.org/docs/prerelease/1.4/crossref.html) article.

## LaTeX Commands in Quarto Files

When adding LaTeX commands in Quarto always use a code block with `{=latex}`:

````latex
```{=latex}
% Some LaTeX code.
```
````

This avoids rendering issues.

## Cross-Referenceable Elements

Quarto allow you to create and reference almost anything by using `div` enclosures. For example:

See @thm-line.

::: {#thm-line}
## Line

The equation of any straight line can be written as:

$$
y = mx + b
$$
:::

Each type of `div` must use pre-defined prefixes. If you don't follow these rules, your document may behave unexpectedly.

For more information about cross-reference elements, see Quarto's [Book Crossrefs](https://quarto.org/docs/books/book-crossrefs.html), [Cross References](https://quarto.org/docs/authoring/cross-references.html), and [Cross-Referenceable Elements](https://quarto.org/docs/prerelease/1.4/crossref.html) articles.

## Freeze and Cache

Avoid using the [`freeze`](https://quarto.org/docs/projects/code-execution.html#freeze) and [`cache`](https://quarto.org/docs/projects/code-execution.html#cache) execution options. If you're having issues updating your document, check whether these options are enabled in your `_quarto.yml` file.

```{=latex}
\end{anexosenv}
```

```yaml
execute:
  cache: false # "Danger, Will Robinson!"
  freeze: false # If you plan to use it, remember to disable it afterward!
```

<!-- annexes end -->
