project:
  output-dir: docs
  pre-render: "R/quarto-pre-render-html.R"
  post-render: "R/quarto-post-render-html.R"

book:
  date: today
  # cover-image: cover.png
  # favicon: cover.png
  sidebar:
    tools:
      - icon: file-earmark-pdf-fill
        href: index.pdf
  chapters:
    - index.qmd
    - part: "Preliminary Pages"
      chapters:
        - qmd/errata.qmd
        - qmd/inscription.qmd
        - qmd/acknowledgments.qmd
        - qmd/epigraph.qmd
        - qmd/vernacular-abstract.qmd
        - qmd/foreign-abstract.qmd
        - qmd/list-of-abbreviations.qmd
        - qmd/list-of-symbols.qmd
        - qmd/list-of-terms.qmd
        - qmd/thesis-outline.qmd
    - part: "Chapters"
      chapters:
        - qmd/introduction.qmd
        - qmd/development.qmd
        - qmd/conclusion.qmd
        - qmd/references.qmd
  appendices:
    - qmd/appendice-1.qmd

citation:
  type: thesis
  url: https://danielvartan.github.io/abnt/
google-scholar: false

format: abnt-html
