project:
  output-dir: docs
  pre-render: "R/_pre-render-html.R"
  post-render: "R/_post-render-html.R"

book:
  date: today
  date-format: "YYYY-MM-DD"
  repo-actions: [edit, issue]
  sidebar:
    tools:
      - icon: file-earmark-pdf-fill
        href: index.pdf
  chapters:
    - index.qmd
    - part: "Preliminary Pages"
      chapters:
        - qmd/errata.qmd
        - qmd/inscription.qmd
        - qmd/acknowledgments.qmd
        - qmd/epigraph.qmd
        - qmd/vernacular-abstract.qmd
        - qmd/foreign-abstract.qmd
        - qmd/list-of-abbreviations.qmd
        - qmd/list-of-symbols.qmd
    - part: "Chapters"
      chapters:
        - qmd/introduction.qmd
        - qmd/development.qmd
        - qmd/conclusion.qmd
    - qmd/references.qmd
    - qmd/glossary.qmd
  appendices:
    - qmd/appendix-1.qmd
    - qmd/pdf-settings.qmd
    - qmd/annex-1.qmd

citation:
  type: thesis
  url: https://danielvartan.github.io/abnt/
google-scholar: false

format: abnt-html
