project:
  output-dir: pdf
  pre-render: "R/quarto-pre-render-pdf.R"
  post-render: "R/quarto-post-render-pdf.R"

# See  <https://quarto.org/docs/books/>.
# See <https://quarto.org/docs/reference/projects/books.html>.
book:
  date: today
  date-format: "YYYY"
  chapters:
    - index.qmd
    - qmd/development.qmd
    - qmd/conclusion.qmd
  appendices:
    - qmd/appendice-1.qmd
    - qmd/settings.qmd

format:
  abnt-pdf:
    zotero: true
    location: "[City]"
    supervisor: "[Supervisor's full name]"
    cosupervisor: "[Co-supervisor's full name]"
    academic-title: "[Master/PhD]"
    academic-degree: "[Master of Science/Doctor of Science]"
    type-of-work: "[Dissertation/Thesis]"
    area-of-concentration: "[Area of concentration]"
    university: "[University]"
    school: "[School/Department]"
    program: "[Graduate program]"
    version-note: "[Original/Revised version]"
    include-in-header: tex/include-in-header.tex
    include-before-body: tex/include-before-body.tex
    include-after-body: tex/include-after-body.tex
